"""circular reference

Revision ID: 0da8edbb80bc
Revises: b027f6085aa9
Create Date: 2021-01-22 12:29:52.551375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0da8edbb80bc'
down_revision = 'b027f6085aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leader_project_assc')
    op.drop_table('author_project_assc')
    op.drop_constraint('project_ibfk_2', 'project', type_='foreignkey')
    op.drop_column('project', 'leader_id')
    op.add_column('user', sa.Column('leading_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'project', ['leading_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'leading_id')
    op.add_column('project', sa.Column('leader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('project_ibfk_2', 'project', 'user', ['leader_id'], ['id'])
    op.create_table('author_project_assc',
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name='author_project_assc_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='author_project_assc_ibfk_2'),
    sa.PrimaryKeyConstraint('author_id', 'project_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('leader_project_assc',
    sa.Column('leader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], name='leader_project_assc_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='leader_project_assc_ibfk_2'),
    sa.PrimaryKeyConstraint('leader_id', 'project_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
