"""LeaderProject assoc table deleted

Revision ID: 1f4a3e5ba8b8
Revises: b56ed1bc5a20
Create Date: 2021-01-22 15:44:18.408608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f4a3e5ba8b8'
down_revision = 'b56ed1bc5a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leader_project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_project',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='leader_project_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='leader_project_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'project_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
