"""public field added to project table

Revision ID: 3ec707ae96ff
Revises: ab8ce088d027
Create Date: 2021-01-21 14:37:00.294520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec707ae96ff'
down_revision = 'ab8ce088d027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'public')
    # ### end Alembic commands ###
