"""project permissions added

Revision ID: 56e62ce8435e
Revises: 0da8edbb80bc
Create Date: 2021-01-22 12:50:30.857013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56e62ce8435e'
down_revision = '0da8edbb80bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator_project',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('leader', sa.Boolean(), nullable=True),
    sa.Column('add_task', sa.Boolean(), nullable=True),
    sa.Column('delete_task', sa.Boolean(), nullable=True),
    sa.Column('done_task', sa.Boolean(), nullable=True),
    sa.Column('store_task', sa.Boolean(), nullable=True),
    sa.Column('add_collaborator', sa.Boolean(), nullable=True),
    sa.Column('delete_collaborator', sa.Boolean(), nullable=True),
    sa.Column('update_charges', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'leading_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('leading_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'project', ['leading_id'], ['id'])
    op.drop_table('collaborator_project')
    # ### end Alembic commands ###
